sudo: required

services:
  - docker

env:
  global:
    - NAME=jupyter-notebook
    - VERSION=${TRAVIS_BRANCH}

script:
  - touch dsn.ini
  - docker build -t ${NAME}:${VERSION} --rm .
  - docker-compose build
